oioioi

diff --git a/old b/old
--- a/old
+++ b/old
@@ -1,3 +1,96 @@
+
+## This function restores backup functionality with -R flag after a restore
+restore_backup_functionality(){
+	echo "Restoring backup functionality by recreating root dataset on backup pool..."
+
+	## Set send and receive pool
+	backup_dataset="$1"
+	local send_pool=$(echo "${backup_dataset}" | awk -F/ '{print $2}')
+	local receive_pool=$(echo "${backup_dataset}" | awk -F/ '{print $1}')
+
+	## Define backup_dataset
+	local backup_dataset="${receive_pool}/${send_pool}"
+
+	## Set ssh prefix if ssh host is specified
+	if [ -n "$2" ]; then
+		local ssh_host="$2"	
+		if [ -n "$3" ]; then
+			local ssh_port="-p $3"
+		fi
+		local ssh_prefix="ssh ${ssh_host} ${ssh_port}"
+	fi
+
+	## Rename receive_pool/send_pool to receive_pool/send_pool_TMP
+	if ${ssh_prefix} zfs rename "${backup_dataset}" "${backup_dataset}_TMP"; then
+		echo "Renamed ${backup_dataset} to ${backup_dataset}_TMP"
+	else
+		echo "Error: failed renaming ${backup_dataset} to ${backup_dataset}_TMP"
+		exit 1
+	fi
+
+	## Create local snapshot to have at least one snapshot to send for root dataset
+	zorra zfs snapshot "${send_pool}" -t restore-sync
+
+	## Send/receive only root dataset as full send (push)
+	echo "Recreating root dataset on backup pool..."
+	local latest_root_snapshot=$(zfs list -H -t snap -o name -s creation "${send_pool}" | tail -n 1)
+	if zfs send -b -w "${latest_root_snapshot}" | ${ssh_prefix} zfs receive -v "${backup_dataset}"; then
+		echo "Recreated root dataset '${backup_dataset}' on backup pool"
+	else
+		echo "Error: failed to send/receive '${latest_root_snapshot}' into '${backup_dataset}'"
+		#exit 1
+	fi
+
+	## Rename all first-level datasets in _tmp dataset to original name
+	echo "Renaming child datasets..."
+	for dataset in $(${ssh_prefix} zfs list -H -o name -r "${backup_dataset}_TMP" | sed -n "s|^${backup_dataset}_TMP/\([^/]*\).*|${backup_dataset}_TMP/\1|p" | sort -u); do
+		if ${ssh_prefix} zfs rename "${dataset}" "${dataset/${backup_dataset}_TMP/${backup_dataset}}"; then
+			echo "Renamed ${dataset} to ${dataset/${backup_dataset}_TMP/${backup_dataset}}"
+		else
+			echo "Error: failed to rename ${dataset} to ${dataset/${backup_dataset}_TMP/${backup_dataset}}"
+			#exit 1
+		fi
+	done
+	
+	## Get all first-level datasets (since root dataset cannot be restored, after a full pool restore the (not restored) root dataset has no matching snapshots on backup pool)
+	local send_datasets=$(zfs list -H -o name -r "${send_pool}" | sed -n "s|^${send_pool}/\([^/]*\).*|${send_pool}/\1|p" | sort -u)
+	if [ -z "${send_datasets}" ]; then echo "Error: pool '${send_pool}' does not exist or has no child datasets to backup"; exit 1; fi
+
+	## Send/receive all first-level datasets including children (-R flag) with verbosity on (-v flag)
+	for send_dataset in ${send_datasets}; do
+		## Get latest snapshot on sending side
+		local latest_send_snapshot=$(zfs list -H -t snap -o name -s creation "${send_dataset}" | tail -n 1)
+		if [ -z "${latest_send_snapshot}" ]; then echo "Error: target '${send_dataset}' does not exist or has no snapshots to backup"; exit 1; fi
+
+		## Set receive dataset
+		local receive_dataset="${receive_pool}/${send_dataset}"
+
+		## Get latest snapshot on receiving side, set incremental if it exists
+		local latest_receive_snapshot=$(${ssh_prefix} zfs list -H -t snap -o name -s creation "${receive_dataset}" | tail -n 1)
+		if [ -n "${latest_receive_snapshot}" ]; then
+			local incremental_snapshot="-I ${latest_receive_snapshot#*@}"
+		else
+			echo "No received snapshot found, executing a full send/receive..."
+		fi
+
+		## Execute send/receive (push)
+		if zfs send -b -w -R ${incremental_snapshot} "${latest_send_snapshot}" | ${ssh_prefix} zfs receive -v "${receive_dataset}"; then
+			echo "Successfully backed up '${latest_send_snapshot}' into '${receive_dataset}'"
+		else
+			echo "Failed to send/receive '${latest_send_snapshot}'$([ -n "${incremental_snapshot}" ] && echo " from incremental '${incremental_snapshot}'") into '${receive_dataset}'"
+			#exit 1
+		fi
+	done
+
+	## Result
+	echo
+	echo "Successfully recreated root dataset on backup pool"
+	echo "Verify backup functionality, and afterwards delete '${backup_dataset}_TMP' on the backup server"
+	echo
+}
+
+################################################################################################################
+
 pull_backup_old(){
 	## Set send and receive pool
 	local send_pool="$1"
