oi

diff --git a/old b/old
--- a/old
+++ b/old
@@ -1,22 +1,21 @@
 
 
-
-
-
+mount_datasets() {
+    for dataset in $1; do
+        echo "Mounting ${dataset}"
+        if ! mount_error=$(zfs mount "${dataset}" 2>&1) && [[ ! "${mount_error}" =~ "filesystem already mounted" ]]; then
+            echo -e "Cannot mount ${dataset}"
+            echo -e "Error: ${mount_error}"
+            echo -e "Overview of mounted datasets:"
+            overview_mountpoints
+            exit 1
+        fi
+    done
+}
 
 
 
 ################################################################################################################
-
-
-
-
-
-
-
-
-
-
 
 
 	## Create boot entry with efibootmgr
