uppie

diff --git a/zorra b/zorra
--- a/zorra
+++ b/zorra
@@ -46,6 +46,7 @@ set_zbm_timeout=false
 set_refind_timeout=false
 set_refind_theme=false
 auto_unlock_pool=false
+change_key=false
 
 trap 'if [ $? -eq 1 ]; then
 	cat <<-EOF
@@ -53,12 +54,13 @@ trap 'if [ $? -eq 1 ]; then
 		ZoRRA options:
 		--debootstrap-install
 		--setup-remote-access [--recreate-host-keys]
-		--add-authorized-key (add:<public_ssh_key> | user:<user>)
 		--clear-authorized-keys
+		--add-authorized-key (add:<public_ssh_key> | user:<user>)
 		--set-zbm-timeout [<integer> | 0 (equals zbm.skip) | -1 (equals zbm.show)]
 		--set-refind-timeout [<integer>]
-		--set-refind-theme [<https//..theme.git> <themename/configname.conf>]
+		--set-refind-theme [(<https//..theme.git> <themename/configname.conf>)]
 		--auto-unlock-pool (<poolname>)
+		--change-key (<new_passphrase>)
 
 	EOF
 fi' EXIT
@@ -75,6 +77,27 @@ while [[ $# -gt 0 ]]; do
 		;;
 		--recreate-host-keys)
 			recreate_dropbear_host_keys=true
+		;;
+		--clear-authorized-keys)
+			clear_authorized_keys=true
+		;;
+		--add-authorized-key)
+			add_authorized_key=true
+			ssh_user=""
+			ssh_authorized_key=""
+			if [[ "${2}" == add:* && "${2#*:}" != "" ]]; then
+				ssh_authorized_key="${2#*:}"
+			elif [[ "${2}" == user:* ]]; then
+				ssh_user="${2#*:}"
+				if ! id "${ssh_user}" &>/dev/null; then
+					echo "User '${ssh_user}' does not exist."
+					exit 1
+				fi
+			else
+				echo "Missing/wrong input parameter '${2}' for ${1}"
+				exit 1
+			fi
+			shift
 		;;
 		--set-zbm-timeout)
 			set_zbm_timeout=true
@@ -100,38 +123,6 @@ while [[ $# -gt 0 ]]; do
 				exit 1
 			fi
 		;;
-		--clear-authorized-keys)
-			clear_authorized_keys=true
-		;;
-		--add-authorized-key)
-			add_authorized_key=true
-			ssh_user=""
-			ssh_authorized_key=""
-			if [[ "${2}" == add:* && "${2#*:}" != "" ]]; then
-				ssh_authorized_key="${2#*:}"
-			elif [[ "${2}" == user:* ]]; then
-				ssh_user="${2#*:}"
-				if ! id "${ssh_user}" &>/dev/null; then
-					echo "User '${ssh_user}' does not exist."
-					exit 1
-				fi
-			else
-				echo "Missing/wrong input parameter '${2}' for ${1}"
-				exit 1
-			fi
-			shift
-		;;
-		--auto-unlock-pool)
-			auto_unlock_pool=true
-			auto_unlock_pool_name=""
-			if  [[ -n "${2}" && "${2}" != --* ]]; then
-				auto_unlock_pool_name="$2"
-			else
-				echo "Missing/wrong input parameter '${2}' for ${1}"
-				exit 1
-			fi
-			shift
-		;;
 		--set-refind-theme)
 			set_refind_theme=true
 			if [[ -z "${2}" || "${2}" == --* ]]; then
@@ -147,6 +138,20 @@ while [[ $# -gt 0 ]]; do
 				echo "Missing/wrong input parameters '${2}' and '${3}' for ${1}"
 				exit 1
 			fi
+		;;
+		--auto-unlock-pool)
+			auto_unlock_pool=true
+			auto_unlock_pool_name=""
+			if  [[ -n "${2}" && "${2}" != --* ]]; then
+				auto_unlock_pool_name="$2"
+			else
+				echo "Missing/wrong input parameter '${2}' for ${1}"
+				exit 1
+			fi
+			shift
+		;;
+		--change-key)
+			change_key=true
 		;;
 		*)
 			echo "Missing/wrong input parameter '${1}' for ${0}"
